// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelInsuranceAuction.Data;

#nullable disable

namespace TravelInsuranceAuction.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128141306_SeedInsuranceRequestTable")]
    partial class SeedInsuranceRequestTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelInsuranceAuction.Models.InsuranceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfTravelers")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId");

                    b.ToTable("InsuranceRequests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            Destination = "London",
                            EndDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            NumberOfTravelers = 2,
                            StartDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            RequestId = 2,
                            Destination = "Paris",
                            EndDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            NumberOfTravelers = 2,
                            StartDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            RequestId = 3,
                            Destination = "Lisabon",
                            EndDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            NumberOfTravelers = 4,
                            StartDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
